In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import string

In [2]:
import pandas as pd

data = pd.read_csv(r"D:\tejas_workbench_proj\Navie_bayes_project\spam.tsv",
                   sep="\t",
                   names = ["Class","Message"])

data.head(10)
    

Class                                            Message
0   ham  I've been searching for the right words to tha...
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...
2   ham  Nah I don't think he goes to usf, he lives aro...
3   ham  Even my brother is not like to speak with me. ...
4   ham               I HAVE A DATE ON SUNDAY WITH WILL!!!
5   ham  As per your request 'Melle Melle (Oru Minnamin...
6  spam  WINNER!! As a valued network customer you have...
7  spam  Had your mobile 11 months or more? U R entitle...
8   ham  I'm gonna be home soon and i don't want to tal...
9  spam  SIX chances to win CASH! From 100 to 20,000 po...

import os
print(os.getcwd())

In [3]:
data.iloc[:,0]

0        ham
1       spam
2        ham
3        ham
4        ham
        ... 
5562    spam
5563     ham
5564     ham
5565     ham
5566     ham
Name: Class, Length: 5567, dtype: object

In [4]:
data["length"] = data["Message"].apply(len)

In [5]:
data

Class                                            Message  length
0      ham  I've been searching for the right words to tha...     196
1     spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
2      ham  Nah I don't think he goes to usf, he lives aro...      61
3      ham  Even my brother is not like to speak with me. ...      77
4      ham               I HAVE A DATE ON SUNDAY WITH WILL!!!      36
...    ...                                                ...     ...
5562  spam  This is the 2nd time we have tried 2 contact u...     160
5563   ham               Will ü b going to esplanade fr home?      36
5564   ham  Pity, * was in mood for that. So...any other s...      57
5565   ham  The guy did some bitching but I acted like i'd...     125
5566   ham                         Rofl. Its true to its name      26

[5567 rows x 3 columns]

In [6]:
data.describe()

length
count  5567.000000
mean     80.450153
std      59.891023
min       2.000000
25%      36.000000
50%      62.000000
75%     122.000000
max     910.000000

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5567 entries, 0 to 5566
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Class    5567 non-null   object
 1   Message  5567 non-null   object
 2   length   5567 non-null   int64 
dtypes: int64(1), object(2)
memory usage: 130.6+ KB


In [8]:
data["length"].min()

2

In [9]:
data.loc[data["length"] == data["length"].min()].iloc[0]

Class      ham
Message     Ok
length       2
Name: 1920, dtype: object

In [10]:
data.loc[:5]

Class                                            Message  length
0   ham  I've been searching for the right words to tha...     196
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
2   ham  Nah I don't think he goes to usf, he lives aro...      61
3   ham  Even my brother is not like to speak with me. ...      77
4   ham               I HAVE A DATE ON SUNDAY WITH WILL!!!      36
5   ham  As per your request 'Melle Melle (Oru Minnamin...     160

In [11]:
data["length"]==910

0       False
1       False
2       False
3       False
4       False
        ...  
5562    False
5563    False
5564    False
5565    False
5566    False
Name: length, Length: 5567, dtype: bool

In [12]:
data.loc[data["length"]==data["length"].max()]

Class                                            Message  length
1080   ham  For me the love should start with attraction.i...     910

In [13]:
data[data["length"]==910]["Message"]

1080    For me the love should start with attraction.i...
Name: Message, dtype: object

### text preprocessing


In [14]:
data["Target"]=data["Class"].map({"spam":0,"ham":1})

In [15]:
data

Class                                            Message  length  Target
0      ham  I've been searching for the right words to tha...     196       1
1     spam  Free entry in 2 a wkly comp to win FA Cup fina...     155       0
2      ham  Nah I don't think he goes to usf, he lives aro...      61       1
3      ham  Even my brother is not like to speak with me. ...      77       1
4      ham               I HAVE A DATE ON SUNDAY WITH WILL!!!      36       1
...    ...                                                ...     ...     ...
5562  spam  This is the 2nd time we have tried 2 contact u...     160       0
5563   ham               Will ü b going to esplanade fr home?      36       1
5564   ham  Pity, * was in mood for that. So...any other s...      57       1
5565   ham  The guy did some bitching but I acted like i'd...     125       1
5566   ham                         Rofl. Its true to its name      26       1

[5567 rows x 4 columns]

In [16]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [17]:
i=["a","b","c"]
"".join(i)

'abc'

In [61]:
str1 =  data["Message"][1]
str1


"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [19]:
type(data)

pandas.core.frame.DataFrame

In [20]:
j= [i for i in  str1 if i not in string.punctuation]

In [21]:
"".join(j)

'Ive been searching for the right words to thank you for this breather I promise i wont take your help for granted and will fulfil my promise You have been wonderful and a blessing at all times'

In [22]:
def remove_punct(text):
    text ="".join([text for text in text if text not in string.punctuation])
    return text.lower()

data["text_clean"] = data["Message"].apply(remove_punct)


In [23]:
data

Class                                            Message  length  Target  \
0      ham  I've been searching for the right words to tha...     196       1   
1     spam  Free entry in 2 a wkly comp to win FA Cup fina...     155       0   
2      ham  Nah I don't think he goes to usf, he lives aro...      61       1   
3      ham  Even my brother is not like to speak with me. ...      77       1   
4      ham               I HAVE A DATE ON SUNDAY WITH WILL!!!      36       1   
...    ...                                                ...     ...     ...   
5562  spam  This is the 2nd time we have tried 2 contact u...     160       0   
5563   ham               Will ü b going to esplanade fr home?      36       1   
5564   ham  Pity, * was in mood for that. So...any other s...      57       1   
5565   ham  The guy did some bitching but I acted like i'd...     125       1   
5566   ham                         Rofl. Its true to its name      26       1   

                                             text_clean  
0     ive been searching for the right words to than...  
1     free entry in 2 a wkly comp to win fa cup fina...  
2     nah i dont think he goes to usf he lives aroun...  
3     even my brother is not like to speak with me t...  
4                     i have a date on sunday with will  
...                                                 ...  
5562  this is the 2nd time we have tried 2 contact u...  
5563                will ü b going to esplanade fr home  
5564  pity  was in mood for that soany other suggest...  
5565  the guy did some bitching but i acted like id ...  
5566                          rofl its true to its name  

[5567 rows x 5 columns]

In [24]:
data.loc[data["Class"]=="ham","Class"]=1

In [25]:
data.loc[data["Class"]=="spam","Class"]=0

In [26]:
data

Class                                            Message  length  Target  \
0        1  I've been searching for the right words to tha...     196       1   
1        0  Free entry in 2 a wkly comp to win FA Cup fina...     155       0   
2        1  Nah I don't think he goes to usf, he lives aro...      61       1   
3        1  Even my brother is not like to speak with me. ...      77       1   
4        1               I HAVE A DATE ON SUNDAY WITH WILL!!!      36       1   
...    ...                                                ...     ...     ...   
5562     0  This is the 2nd time we have tried 2 contact u...     160       0   
5563     1               Will ü b going to esplanade fr home?      36       1   
5564     1  Pity, * was in mood for that. So...any other s...      57       1   
5565     1  The guy did some bitching but I acted like i'd...     125       1   
5566     1                         Rofl. Its true to its name      26       1   

                                             text_clean  
0     ive been searching for the right words to than...  
1     free entry in 2 a wkly comp to win fa cup fina...  
2     nah i dont think he goes to usf he lives aroun...  
3     even my brother is not like to speak with me t...  
4                     i have a date on sunday with will  
...                                                 ...  
5562  this is the 2nd time we have tried 2 contact u...  
5563                will ü b going to esplanade fr home  
5564  pity  was in mood for that soany other suggest...  
5565  the guy did some bitching but i acted like id ...  
5566                          rofl its true to its name  

[5567 rows x 5 columns]

In [30]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer #its acts like encoder transformation 


In [31]:
ySet =ySet.astype("int")

In [32]:
x_train,x_test,y_train,y_test = train_test_split(xSet,ySet,test_size=0.2,random_state=20)

In [33]:
CV = CountVectorizer(stop_words = "english")

In [34]:
xSet_train_CV = CV.fit_transform(x_train).toarray()

In [35]:
xSet_train_CV

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [40]:
x_test

4727                                keng rocking in ashes
2312               thats cause your old i live to be high
5400                          so how many days since then
5256    i absolutely love south park i only recently s...
1679       already am squatting is the new way of walking
                              ...                        
999               ltgt  am i think should say on syllabus
5414    im at bruce amp fowler now but im in my moms c...
2475    sppok up ur mob with a halloween collection of...
2761             and  picking them up from various points
3354    i dont run away frm u i walk slowly amp it kil...
Name: text_clean, Length: 1114, dtype: object

In [36]:
y_train

226     1
3349    1
1205    1
3214    1
919     1
       ..
1607    1
3915    1
1428    1
4367    1
2522    1
Name: Class, Length: 4453, dtype: int32

In [37]:
NB = MultinomialNB()

In [38]:
NB.fit(xSet_train_CV,y_train)

MultinomialNB()

In [41]:
x_test_cv = CV.transform(x_test)

In [43]:
y_pred = NB.predict(x_test_cv)

In [44]:
from sklearn.metrics import classification_report

In [45]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92       137
           1       0.99      0.99      0.99       977

    accuracy                           0.98      1114
   macro avg       0.95      0.95      0.95      1114
weighted avg       0.98      0.98      0.98      1114



In [46]:
pd.crosstab(y_test,y_pred)

col_0    0    1
Class          
0      126   11
1       11  966

In [74]:
msg = input("Enter Message: ") # to get the input message
msgInput = CV.transform([msg]) #
predict = NB.predict(msgInput)
#print(predict)
if(predict[0]==0):
    print("------------------------MESSAGE-SENT-[CHECK-SPAM-FOLDER]---------------------------")
else:
    print("---------------------------MESSAGE-SENT-[CHECK-INBOX]------------------------------")

Enter Message:  Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"


[0]
------------------------MESSAGE-SENT-[CHECK-SPAM-FOLDER]---------------------------


### BAG OF WORDS

In [77]:
documents = ["Dog bites man.", "Man bites dog.", "Dog eats meat.", "Man eats food."]
processed_docs = [doc.lower().replace(".","")for doc in documents]
print("our corpus",processed_docs) 

our corpus ['dog bites man', 'man bites dog', 'dog eats meat', 'man eats food']


In [79]:
count_vect = CountVectorizer()
bow_rep = count_vect.fit_transform(processed_docs)
print("Our vocabulary",count_vect.vocabulary_)

Our vocabulary {'dog': 1, 'bites': 0, 'man': 4, 'eats': 2, 'meat': 5, 'food': 3}


In [80]:
print("BoW representation for 'dog bites man': ", bow_rep[0].toarray())
print("BoW representation for 'man bites dog: ",bow_rep[1].toarray())


BoW representation for 'dog bites man':  [[1 1 0 0 1 0]]
BoW representation for 'man bites dog:  [[1 1 0 0 1 0]]


In [87]:
bow_rep[0].toarray()

array([[1, 1, 0, 0, 1, 0]], dtype=int64)

In [88]:
temp= count_vect.transform(["dog and dog are friend"])
print("bow representation for 'dog and dog are friend'",temp.toarray())

bow representation for 'dog and dog are friend' [[0 2 0 0 0 0]]


### TF-IDF

In [91]:
x=data["text_clean"]
y=data["Class"]

y


0       1
1       0
2       1
3       1
4       1
       ..
5562    0
5563    1
5564    1
5565    1
5566    1
Name: Class, Length: 5567, dtype: object

In [92]:
y=y.astype("int")

In [95]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
x_proc = tf.fit_transform(x)

In [100]:
x_proc.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [106]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_proc,y,random_state =10)

In [108]:
x_train.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [123]:
from sklearn.naive_bayes import BernoulliNB
nb= BernoulliNB()
nb.fit(x_train,y_train)

BernoulliNB()

In [124]:
y_pred1 = nb.predict(x_test)

In [125]:
from sklearn.metrics import classification_report,confusion_matrix

In [126]:
print("classification_report",classification_report(y_test,y_pred1))

classification_report               precision    recall  f1-score   support

           0       0.99      0.82      0.89       196
           1       0.97      1.00      0.98      1196

    accuracy                           0.97      1392
   macro avg       0.98      0.91      0.94      1392
weighted avg       0.97      0.97      0.97      1392



In [127]:
pd.crosstab(y_test,y_pred1)

col_0    0     1
Class           
0      160    36
1        2  1194